services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./data:/mlflow/data
    environment:
      - MLFLOW_DISABLE_SECURITY_MIDDLEWARE=true
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/data/mlflow.db
      --artifacts-destination /mlflow/data/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
    restart: unless-stopped
